### ISSUE TITLE
how to use at node js

### ISSUE THREAD

**Issue by santoshshinde2012** [gabrielgisoldo/vimeoUploader#1]
I have to use this library at node js side , Can you please give me sample example for same?

Thanks.

**Comment by gabrielgisoldo** [comment]
So, this library wasn't made to work with nodeJS, it's actually to use it directly on the browser.

If you want to work with NodeJS, i recommend you to use the official library.
You can find it here: https://github.com/vimeo/vimeo.js

Sincerely.
